jokes = {
"Jul qvq gur Zntr ershfr gb funer uvf yhapu? Orpnhfr ur qvqa'g jnag gb Nepnar Vagryyrpg nalbar!",
"Jung qb lbh pnyy n Zntr jub'f nyfb n wnavgbe? N Sebfg Abin Pyrnare.",
"Ubj qbrf n Zntr znxr n phc bs grn? Jvgu Nepnar Oerj.",
"Jul qvq gur Zntr orpbzr n yhzorewnpx? Orpnhfr ur ybirf hfvat Sebfg Pubc.",
"Jung qb lbh pnyy n tebhc bs Zntrf cynlvat fbppre? N Oyvax Fdhnq.",
"Jul qvq gur Zntr ershfr gb jngpu ubeebe zbivrf? Orpnhfr ur'f nyjnlf trggvat Cbylzbecurq vagb n furrc.",
"Jul qvq gur Zntr orpbzr n onegraqre? Orpnhfr ur'f terng ng zvkvat Nepnar Pbpxgnvyf.",
"Jul qb Zntrf znxr onq zrpunavpf? Orpnhfr gurl nyjnlf jnag gb Sebfg Abin gur ratvar.",
"Jung qb lbh pnyy n tebhc bs Zntrf fghqlvat gbtrgure? Gur Nepnar Fpubynef.",
"Ubj qb lbh xabj vs n Uhagre unf orra va lbhe ubhfr? Gurer'f n genvy bs qrnq crgf.",
"Jul qvq gur Uhagre ershfr gb uhag qrre? Orpnhfr ur jnf nsenvq bs orvat n Znexfznafuvc gnetrg.",
"Jung'f n Uhagre'f snibevgr GI fubj? Tnzr bs Gubeaf.",
"Jung'f n Uhagre'f snibevgr vpr pernz synibe? Znexfznafuvc Zbpun.",
"Ubj znal Uhagref qbrf vg gnxr gb punatr n yvtug ohyo? Whfg bar, ohg ur'yy arrq gb hfr Rntyr Rlr.",
"Ubj qbrf n Uhagre znxr n fnaqjvpu? Jvgu Nvzrq Fubg-yrgghpr.",
"Jul qb Uhagref znxr onq pursf? Orpnhfr gurl nyjnlf gel gb Uhagre'f Znex gur sbbq.",
"Jul qvq gur Qrzba Uhagre ershfr gb rng qrffreg? Orpnhfr vg unq gbb znal Vyyvqnev pnybevrf.",
"Jung'f n Qrzba Uhagre'f snibevgr cvmmn gbccvat? Vyyvqnev Fnhfntr.",
"Ubj qb lbh xabj vs n Qrzba Uhagre vf ylvat? Ur unf n Iratrshy Ergerng.",
"Jung'f n Qrzba Uhagre'f snibevgr prerny? Vyyvqnev-B'f.",
"Jung qb lbh pnyy n Jneybpx jub'f nyfb n pbbx? N Sry Purs.",
"Jul qvq gur Jneybpx trg n wbo nf n pnfuvre? Ur ybirf pbhagvat Fbhy Funeqf.",
"Jul qvq gur Jneybpx trg onaarq sebz gur yvoenel? Ur xrcg gelvat gb Fhzzba Obbxf.",
"Jung qb lbh pnyy n Jneybpx jub'f nyfb n tneqrare? N Sry Oybbzre.",
"Jung qb lbh pnyy n tebhc bs Jneybpxf pbbxvat gbtrgure? Gur Sry Synzrf.",
"Jung'f n Jneybpx'f snibevgr qevax? Sry-hppvab.",
"Jul qvq gur Jneybpx orpbzr n cnvagre? Orpnhfr ur ybirf gb Fhzzba Qrzbavp Oehfufgebxrf.",
"Jul qvq gur Ebthr pebff gur ebnq? Gb trg gb gur bgure Funqbjfgrc.",
"Jul qba'g Ebthrf rire trg pnhtug? Orpnhfr gurl unir Inavfu-vat fxvyyf.",
"Jul qvq gur Ebthr orpbzr n oneore? Orpnhfr ur'f n Phg Nobir gur erfg.",
"Jul qb Ebthrf znxr onq svfurezra? Orpnhfr gurl nyjnlf jnag gb Nzohfu gur svfu.",
"Jul qb Ebthrf znxr onq pbbxf? Orpnhfr gurl nyjnlf gel gb Fuvi gur vaterqvragf.",
"Jul qvq gur Ebthr orpbzr n qrgrpgvir? Ur ybirf gb Cvpx Cbpxrg.",
"Ubj qb lbh xabj vs n Ebthr vf ylvat? Uvf Qnttre vf nyjnlf Cbvfbarq.",
"Jung qb lbh pnyy n tebhc bs Ebthrf gelvat gb or fgrnygul? Gur Fvyrag Oynqrf.",
"Jung'f n Cnynqva'f snibevgr zbivr? Qvivar Vagreiragvba.",
"Jung qb lbh pnyy n tebhc bs Cnynqvaf jub bayl hfr gurve ohooyrf? Gur Ubyl Fuvryqf.",
"Jung qb lbh pnyy n Cnynqva jub pna'g pnfg fcryyf? N Ubyl Zbyl.",
"Ubj znal Cnynqvaf qbrf vg gnxr gb punatr n yvtug ohyo? Abar, gurl whfg Enqvnag Yvtug vg hc.",
"Ubj znal Cnynqvaf qbrf vg gnxr gb fperj va n yvtug ohyo? Gjb, ohg gurl unir gb or Ubyl.",
"Jung'f n Cnynqva'f snibevgr sehvg? Ubyl Nibpnqb.",
"Jul qb Cnynqvaf znxr onq unve fglyvfgf? Orpnhfr gurl nyjnlf jnag gb Unzzre bs Whfgvpr lbhe unve.",
"Ubj znal Cnynqvaf qbrf vg gnxr gb pngpu n svfu? Abar, gurl'yy whfg oyrff gur svfuvat ebq.",
"Ubj znal Cnynqvaf qbrf vg gnxr gb punatr n gver? Abar, gurl whfg Ubyl Yvtug gur pne.",
"Ubj qb lbh xabj vs n Cnynqva vf ylvat? Uvf Nhen vf nyjnlf Qribgvba.",
"Jul qvq gur Cnynqva orpbzr n sversvtugre? Orpnhfr ur ybirf gb Rkgvathvfu Synzrf.",
"Jul qba'g Qehvqf trg fvpx? Gurl unir n ybg bs Angher'f Fjvsgarff.",
"Ubj qb lbh xabj vs n Qehvq vf znq? Ur'f Gerr-zraqbhf-yl natel.",
"Jung qb lbh pnyy n tebhc bs Qehvqf zrqvgngvat gbtrgure? N Ebbg Pvepyr.",
"Jul qba'g Qehvqf rire trg gverq? Gurl unir n ybg bs Raqyrff Tebjgu.",
"Jul qvq gur Qehvq orpbzr n tneqrare? Orpnhfr ur ybirf gb Phygvingr Yvsr.",
"Ubj znal Qrngu Xavtugf qbrf vg gnxr gb punatr n yvtug ohyo? Whfg bar, ohg ur'yy arrq gb hfr Qrngu Tevc.",
"Jul qb Qrngu Xavtugf ungr chaf? Orpnhfr gurl'er nyjnlf trggvat Sebfgovggra.",
"Ubj qb lbh xabj vs n Qrngu Xavtug vf ylvat? Uvf abfr vf nyjnlf Eharsbetrq.",
"Ubj znal Qrngu Xavtugf qbrf vg gnxr gb fgneg n pnzcsver? Whfg bar, ohg ur'yy arrq gb hfr Punvaf bs Vpr.",
"Jul qb Qrngu Xavtugf nyjnlf jrne tybirf? Orpnhfr gurve unaqf ner nyjnlf Pbyq nf Vpr.",
"Ubj znal Qrngu Xavtugf qbrf vg gnxr gb cnvag n jnyy? Whfg bar, ohg ur'yy arrq gb hfr Qrngu naq Qrpnl.",
"Jul qvq gur Qrngu Xavtug orpbzr n gbhe thvqr? Orpnhfr ur ybirf gb tvir gur Pbyq Fubhyqre.",
"Jung qb lbh pnyy n tebhc bs Funznaf cynlvat zhfvp gbtrgure? N Gbgrz Cbyr Onaq.",
"Jul qvq gur Funzna ershfr gb tb gb gur ornpu? Ur qvqa'g jnag gb or pnhtug va n Evcgvqr.",
"Ubj qb lbh xabj vs n Funzna vf ybfg? Ur'f nyjnlf nfxvat sbe qverpgvbaf gb gur Fcvevg Urnyre.",
"Jul qvq gur Funzna orpbzr n jrngurezna? Orpnhfr ur ybirf pnfgvat Fgbezfgevxr.",
"Jung'f n Funzna'f snibevgr navzny? Gur Guhaqre Yvmneq.",
"Jul qb Jneevbef nyjnlf unir gur orfg cvpxhc yvarf? Orpnhfr gurl'er nyjnlf punetvat.",
"Jung qb lbh pnyy n tebhc bs Jneevbef cynlvat fbppre? N Punetr Yvar.",
"Jul qb Jneevbef znxr onq pbzrqvnaf? Orpnhfr gurl nyjnlf Punetr gurve chapuyvarf.",
"Jung qb lbh pnyy n tebhc bs Jneevbef cenpgvpvat nepurel? Gur Guhaqreobyg Neebjf.",
"Jung qb lbh pnyy n tebhc bs Jneevbef cynlvat purff? N Punetr naq Purpxzngr.",
"Jung'f gur qvssrerapr orgjrra n Cevrfg naq n znvy pneevre? Gur Cevrfg pna erfheerpg gur qrnq.",
"Jung'f n Cevrfg'f snibevgr fbqn? Ubyl Fcevgr.",
"Jul qvq gur Cevrfg orpbzr n zngu grnpure? Orpnhfr ur ybirf gb nqq Ubyl Ahzoref.",
"Jung'f n Cevrfg'f snibevgr fbat? Ulza bs Ubcr.",
"Jung qb lbh pnyy n tebhc bs Cevrfgf univat n cvpavp? Gur Ubyl Yhapu.",
"Jul qba'g Zbaxf rire trg ybfg? Gurl unir Vaare Crnpr.",
"Jul qb Zbaxf znxr onq onfxrgonyy cynlref? Orpnhfr gurl nyjnlf gel gb hfr Sylvat Frecrag Xvpx.",
"Jung qb lbh pnyy n tebhc bs Zbaxf qbvat lbtn gbtrgure? Gur Mra Znfgref.",
"Jul qb Zbaxf znxr onq fbppre cynlref? Orpnhfr gurl nyjnlf jnag gb hfr Ebyy Xvpx."
}